package models;
// Generated 10-feb-2017 9:21:19 by Hibernate Tools 4.3.1.Final

/**
 * EventoSuscrito generated by hbm2java
 */
public class EventoSuscrito implements java.io.Serializable {

	private Integer idEventoSuscrito;
	private Evento evento;
	private Usuario usuario;
	private String valoracion;
	private String path;

	public EventoSuscrito() {
	}

	public EventoSuscrito(Evento evento, Usuario usuario, String valoracion, String path) {
		this.evento = evento;
		this.usuario = usuario;
		this.valoracion = valoracion;
		this.path = path;
	}

	public Integer getIdEventoSuscrito() {
		return this.idEventoSuscrito;
	}

	public void setIdEventoSuscrito(Integer idEventoSuscrito) {
		this.idEventoSuscrito = idEventoSuscrito;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(String valoracion) {
		this.valoracion = valoracion;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
