package models;
// Generated 13-feb-2017 16:09:05 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nombre;
	private String apellidos;
	private Integer edad;
	private String telefono;
	private String email;
	private String passUsuario;
	private Boolean admin;
	private Set eventoSuscritos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombre, String apellidos, Integer edad, String telefono, String email, String passUsuario,
			Boolean admin, Set eventoSuscritos) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.edad = edad;
		this.telefono = telefono;
		this.email = email;
		this.passUsuario = passUsuario;
		this.admin = admin;
		this.eventoSuscritos = eventoSuscritos;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassUsuario() {
		return this.passUsuario;
	}

	public void setPassUsuario(String passUsuario) {
		this.passUsuario = passUsuario;
	}

	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

	public Set getEventoSuscritos() {
		return this.eventoSuscritos;
	}

	public void setEventoSuscritos(Set eventoSuscritos) {
		this.eventoSuscritos = eventoSuscritos;
	}

}
